apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: servers-check
    labels: "{{ - include "hgs.labels" . | nindent 4 }}"
spec:
    schedule: "*/5 * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: servers-check
                          securityContext:
                            "{{- toYaml .Values.securityContext | nindent 12 }}"
                          image: "{{ .Values.image.repository }}/php:{{ .Values.image.tag | default .Chart.AppVersion }}"
                          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
                          volumeMounts:
                            - name: "env"
                              mountPath: "/app/.env"
                              subPath: ".env"
                            - name: "openrc"
                              mountPath: "/mnt/.openrc"
                              subPath: ".openrc"
                            - name: "id-rsa"
                              mountPath: "/mnt/id_rsa"
                              subPath: "id_rsa"
                          command:
                              - /app/bin/console
                              - app:servers:check
                    restartPolicy: OnFailure
