apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: hello
spec:
    schedule: "*/5 * * * *"
    jobTemplate:
        spec:
            template:
              spec:
                {{- if .Values.imagePullSecret }}
                imagePullSecrets: 
                - name: {{ .Values.imagePullSecret }}
                {{- end }}
                serviceAccountName: {{ include "hgs.serviceAccountName" . }}
                securityContext:
                  {{- toYaml .Values.podSecurityContext | nindent 8 }}
                containers:
                  - name: php
                    securityContext:
                      {{- toYaml .Values.securityContext | nindent 12 }}
                    image: "{{ .Values.image.repository }}/php:{{ .Values.image.tag | default .Chart.AppVersion }}"
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    volumeMounts:
                      - name: "env"
                        mountPath: "/app/.env"
                        subPath: ".env"
                      - name: "openrc"
                        mountPath: "/mnt/.openrc"
                        subPath: ".openrc"
                      - name: "id-rsa"
                        mountPath: "/mnt/id_rsa"
                        subPath: "id_rsa"
                    args:
                    - /app/bin/console
                    - app:servers:check
                  restartPolicy: OnFailure
