apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-env-php
type: Opaque
data:
  .env: |-
    {{ .Values.envFile | b64enc }}
  .openrc: |-
    {{ .Values.openrc | b64enc }}
  id_rsa: |-
    {{ .Values.privateKey | b64enc }}