apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    {{- include "hgs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: php
  selector:
    app: php
    {{- include "hgs.selectorLabels" . | nindent 4 }}
