---
- name: Mount backup vhserver
  hosts: valheim
  gather_facts: no
  tasks:
      - name: Ensure directories exists
        ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0755"
        become: yes
        with_items:
            - /mnt/restic
        vars:
            ansible_ssh_pipelining: true
      - name: Mount VHServer home config directory
        shell: restic mount /mnt/restic
        become: yes
        environment:
            OS_AUTH_URL: https://auth.cloud.ovh.net/v3/
            OS_IDENTITY_API_VERSION: 3
            OS_TENANT_ID: "{{ lookup('env', 'OS_TENANT_ID') }}"
            OS_TENANT_NAME: "{{ lookup('env', 'OS_TENANT_NAME') }}"
            OS_USERNAME: "{{ lookup('env', 'OS_USERNAME') }}"
            OS_PASSWORD: "{{ lookup('env', 'OS_PASSWORD') }}"
            OS_USER_DOMAIN_NAME: "{{ lookup('env', 'OS_USER_DOMAIN_NAME') | default('Default', True) }}"
            OS_PROJECT_DOMAIN_NAME: "{{ lookup('env', 'OS_PROJECT_DOMAIN_NAME') | default('Default', True) }}"
            OS_REGION_NAME: "{{ lookup('env', 'OS_REGION_NAME') | regex_replace('^([A-Z]+)([0-9]+)$', '\\1') }}"
            RESTIC_PASSWORD: "{{ lookup('env', 'SERVER_ID') }}"
            RESTIC_REPOSITORY: swift:backup-valheim:/{{ lookup('env', 'SERVER_ID') }}"
